### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by silvio**
some small fixes

### CODE REVIEW

**Comment by silvio** [comment]
@zo Is this not the right way to contribute?

**Comment by zo** [comment]
@silvio I did my contributions without using github pull requests, but it could be one way to do it.
I'll ask free-electrons team if they can review your pull request on github.

**Comment by pokazef** [comment]
@silvio Thanks for the bugfixes, I'll merge them right away. And sorry for the long delay, I'm still learning the github workflow.

**Comment by silvio** [comment]
Thanks @pokazef. No problem so far. I have hit @zo, he had the most commits so he have to know how to contribute ;-)

**Comment by zo** [comment]
most commits in history last page only ;-)

**Pull request merged**
